### ISSUE TITLE
Timezone configuration lost with persistent volume

### ISSUE THREAD

**Issue by maxxoverclocker** [goricz/docker#1]
If I run a docker pull + docker rm + docker run, I loose my timezone settings. Normally I would just add the ENV for TZ to the run command, but this image doesn't seem to honor this.
`--env TZ=America/Los_Angeles`
I've had other docker images misbehave in this way and my work around would be to just mount the /etc/localtime file to the container as readonly, but this doesn't seem to work with this particular image either...
`--volume /etc/localtime:/etc/localtime:ro`

Is there a file somewhere else that apache or python is reading from that causes this issue?

**Comment by goricz** [comment]
Please use this docker image, you can set timezone via env variable:
https://github.com/XoruX/apps-docker
