### ISSUE TITLE
LWP Version incorrect

### ISSUE THREAD

**Issue by maxxoverclocker** [goricz/docker#2]
Per: https://www.lpar2rrd.com/https.htm the LWP version needs to be 6.04-2, however the docker image defaults to LWP Version: 6.08.

Due to this, vcenter connections do not work:
`Server version unavailable at 'https://FQDN:443/sdk/vimService.wsdl' at /home/lpar2rrd/lpar2rrd/vmware-lib/apps/../VMware/VICommon.pm line 704.`

**Comment by goricz** [comment]
Please use this docker image, it has no problem with vcenter and LWP:
https://github.com/XoruX/apps-docker
